### ISSUE TITLE
Screenshots for wiki

### ISSUE THREAD

**Issue by rob-linton** [Senetas/SureDrop#14]
![image](https://user-images.githubusercontent.com/457335/78208491-3d70d800-74f0-11ea-8b23-bd1a3f673a10.png)

![image](https://user-images.githubusercontent.com/457335/78208592-7c069280-74f0-11ea-980a-bbdf036a436f.png)

**Comment by devamchakrabarty** [comment]
![image](https://user-images.githubusercontent.com/44823602/79975764-d6d34e80-84de-11ea-8321-d1af53b48025.png)

**Comment by devamchakrabarty** [comment]
![image](https://user-images.githubusercontent.com/44823602/79976159-83153500-84df-11ea-9ea3-2995e14baab9.png)

**Comment by devamchakrabarty** [comment]
![image](https://user-images.githubusercontent.com/44823602/79977217-3af71200-84e1-11ea-8fa3-43b0e400d59f.png)

**Comment by devamchakrabarty** [comment]
![image](https://user-images.githubusercontent.com/44823602/79977401-90cbba00-84e1-11ea-8e7c-c5494a6ed0bc.png)

**Comment by devamchakrabarty** [comment]
![image](https://user-images.githubusercontent.com/44823602/79977614-e6a06200-84e1-11ea-89e0-9212f3b1e8c6.png)
